### ISSUE TITLE
shadowsocks_chromeapp 不工作

### ISSUE THREAD

**Issue by braveguywallce** [shadowsocks/shadowsocks-chromeapp#5]
在windows 7 64bit 的环境下安装了nodejs 和 coffeescript, 编译app后，添加到chrome成功。启动app，填入各项参数。但是不能工作，没有作用。

加密方式是 rc4-md5。访问whatismyip.com 提示ip为真实地址，代理没有起到作用。

**Comment by braveguywallce** [comment]
访问whatismyip.com 提示ip仍然为真实ip, 代理没有起到作用。

**Comment by cookie223** [comment]
Similar problem.
Clicking "Save" makes the window disappear and then reappear.
No sign such as "successfully connected". Wondering if "no sign" is how it is supposed to work.

Local environment:
Google Chrome OS
Version 42.0.2311.60 beta (64-bit)
Platform 6812.52.0 (Official Build) beta-channel squawks_freon
Firmware Google_Squawks.5216.152.22

Server:
Amazon Web Serveries, Tokyo
EC2
ubuntu-trusty-14.04-amd64-server-20150123 (ami-20b6aa21)

There should be no problem with server. Android client app works well with the server.

**Comment by meowlab** [comment]
@braveguywallce 本项目只是一个Chrome App 版本的Shadowsocks的客户端，你需要将Chrome配置为使用Socks5代理上网才能起到作用。

**Comment by meowlab** [comment]
@cookie223 Since I'm not good at UI design and development, I just wrote a simple UI which will not display any warning or error message now. I will improve it in later updates.

If you can confirm you have configured to use a SOCKS5 proxy in Chrome correctly (not a SOCKS4 proxy you can configured in Settings UI), you may use background inspect window to see if there are any error message logged into console.

You can open background inspect window by right click the blank area of this app, and choice `inspect background page`. Or go to `chrome://extensions/`, click the `Inspect views: background page` of this app. Report is welcome if you see any unusual message in console.

By the way, I've noticed you are using Chrome OS. In theory, this app could be run on any platform, but I have not chance to test it on Chrome OS. I would appreciate it if you can tell me whether it can work on Chrome OS or not.

**Comment by cookie223** [comment]
@meowlab Thanks for your prompt response. 
*Short answer: Yes, it's working"*
Honestly, I didn't test it thoroughly the first time. To disappear and then reappear with nothing change did not convince me that it is working.
I did encounter with following problem as the screenshot shows. But it's gone after a restart. So probably it is just because another application is using the port. I will come back to you if my guess is not the case.
![screenshot 2015-03-29 at 9 41 44 pm](https://cloud.githubusercontent.com/assets/5301377/6886024/8b44ee18-d662-11e4-868e-e0d82dbecd67.png)
 
For future references, I use [Proxy SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif?hl=en) to set the SOCKS5 proxy for blocked sites.

BTW, if the functions is just like "port forwarding" but not a proxy, with the existence of Windows/OS X Client, I really think Chrome OS users are the majority of who benefits from the project. I cannot figure out why but as a Chromebook user I appreciate your great work!

**Comment by braveguywallce** [comment]
@cookie223 @meowlab 

Yes, it works after I set chromebook as what you had advised.

I will test its performance & stability for further and feed back. 

Thank you very much for this great work!

**Comment by joegege** [comment]
Could you please provide detailed install instructions because I am newbie for chrome os app? Thanks in advance.
"Since this is a development version, node.js and CoffeeScript is required for build. You can run cake build under root directory to build once or use cake watch to watch the code change."

**Comment by meowlab** [comment]
@joegege 
I have no Chrome OS device so I can't tell you how to install nodejs and coffeescript on it. Use Google to search the way maybe a better choice. Or you can install nodejs on windows (download installer form nodejs.org) or linux (use package manager).

After nodejs installed, clone this repo, change directory to the root directory of this app, use `npm install coffeescript` to install coffeescript support, then run `cake build` to build this app.

Finally, copy all files in root directory of this app to Chromebook If you compile it on other device. Goto `chrome://extensions/` and load it, then it should work.


@cookie223 
Sorry I can't understand what you want to express in the last paragraph. Is the "port forwarding" you said like ss-redir?

**Comment by cookie223** [comment]
@joegege Personally I enabled developer mode on my Chrome OS and installed a linux and use it to install nodejs and coffeescrpt and then "run cake build"  on linux. I would suggest you try "run cake build" on other devices since installing a linux on chromebook for just one app is a long way to go. Refer to [This project](https://github.com/dnschneid/crouton) if you want a try. Or maybe you can wait for the compiled version. I hope it will come soon.

@meowlab Sorry for my confusing expression, I am not a cs guy~ I mean, for chrome running on other OS, such as windows or OS X, we can just use windows or OS X shadowsocks client and set the appropriate proxy on chrome.

**Comment by meowlab** [comment]
@cookie223 Yes Windows and OS X have their own client. But I believe this project's aim is becoming a shadowsocks client which doesn't need to download, easy to install and configure, sync with your Google account and cross platform. And now I know there are many Chromebook users are keep tracking of this project, thanks for all your support, let's make it better together :)

**Comment by cookie223** [comment]
@meowlab It will be great to have a light client and it can be synchronized across platforms. I would love to provide whatever help I can. Hopping to see a released version soon. I will help you to test it on chrome OS if needed.
