### ISSUE TITLE
Could not load extension from '/mnt/lfs/src/ss/shadowsocks-chromeapp'. This extension requires Chromium version 41 or greater.

### ISSUE THREAD

**Issue by haobug** [shadowsocks/shadowsocks-chromeapp#6]
Could not load extension from '/mnt/lfs/src/ss/shadowsocks-chromeapp'. This extension requires Chromium version 41 or greater.

**Comment by meowlab** [comment]
Yes it needs chrome version 41 or greater because older version doesn't support `background` permission.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by haobug** [comment]
i have managed get work on SwitchySharp, mixed with g0agent.
because the shadowsocks looks not accept http(s) requests...

chromium sucks more and more as the version num raising. 
could you all please write code support more versions, in someway.

**Comment by meowlab** [comment]
Shadowsocks is a SOCKS5 proxy not a HTTP proxy like goagent. You didn't set correctly in proxy switchysharp.

If you want to use this app in older version of Chromium, you may downgrade version restriction to 33 by modifying `manifest.json`, also you should remove `background` permission declaration in `manifest.json`. Version 33 is the minimal version required because new Socket API was introduced in this version. 

Since this app is develop under Chrome V41, it may not works correctly on older version, if you find any bug, report is welcome.

**Comment by haobug** [comment]
does that mean i config socket5 proxy on chrom does not affect the network flow?
but i have seen the request log. 

and the goagent switchysharp required proxy api is 13+, 
why does the ss extension requires 33+?

another thing i want to get involved in ss,
which code you suggest to get start from?

at last, i am now using(intent to find the 18 version, but not found)
Version 24.0.1305.0 custom (163416)

Epilogue:
>thanks for your reply in english, this could be usefull for foreigh friends.
>>but is there any foreigner need to use ss ;), it's illusion
>wait!
>>yes i am same as you a chinese , using linux with en_US locale,  pasted the error string directly when file this issue.....

**Comment by haobug** [comment]
does that mean i config socket5 proxy on chrom does not affect the network flow?
but i have seen the request log. 

and the goagent switchysharp required proxy api is 13+, 
why does the ss extension requires 33+?

another thing i want to get involved in ss,
which code you suggest to get start from?

at last, i am now using(intent to find the 18 version, but not found)
Version 24.0.1305.0 custom (163416)

Epilogue:
>thanks for your reply in english, this could be usefull for foreigh friends.
>>but is there any foreigner need to use ss ;), it's illusion
>wait!
>>yes i am same as you a chinese , using linux with en_US locale,  pasted the error string directly when file this issue.....

**Comment by haobug** [comment]
does that mean i config socket5 proxy on chrom does not affect the network flow?
but i have seen the request log. 

and the goagent switchysharp required proxy api is 13+, 
why does the ss extension requires 33+?

another thing i want to get involved in ss,
which code you suggest to get start from?

at last, i am now using(intent to find the 18 version, but not found)
Version 24.0.1305.0 custom (163416)

Epilogue:
>thanks for your reply in english, this could be usefull for foreigh friends.
>>but is there any foreigner need to use ss ;), it's illusion
>wait!
>>yes i am same as you a chinese , using linux with en_US locale,  pasted the error string directly when file this issue.....

**Comment by meowlab** [comment]
Yes I know, except for "English is the universal language in open source world ", I also believe maybe it's a good way to practice English lol~

This app is just a shadowsocks client, providing socks5 server on localhost, like goagent providing http proxy server on localhost, but not a proxy management application like switchysharp. So they are different, shadowsocks chrome app version relys on chrome sockets api which was introduced on M33, switchysharp relys on chrome proxy setting api(I guess), so it can support older chrome.

You may find shadowsocks written in your favorite or familiar language at https://github.com/shadowsocks, read it maybe a better choice, in my personal opinion, I suggest you to read the Python version of shadowsocks, because it's the core version and well maintained. Of course, you should have some basic network knowledges, and have the availability to read rfc document.
